# Site settings
title: Muyang Ye
email: muyangye@usc.edu
description: > # keep this and put description below
  Software Engineer and Lifelong Gamer; lie-flatility and triviality
url: "https://muyangye.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/muyang-ye-84084b1a9/"
github_username: muyangye
# twitter_username: gamingportfolio
footer_text: "Copyright © 2023 realYMYPlus. No rights reserved."

# Build settings
markdown: kramdown
permalink: pretty
